- name: Deploy to Server via SSH
  uses: appleboy/ssh-action@v1.0.0

  with:
    host: ${{ secrets.SERVER_HOST }}
    username: ${{ secrets.SERVER_USER }}
    key: ${{ secrets.SERVER_SSH_KEY_BASE64 }}
    port: 22
    key_format: base64

    script: |
      cd nutaan-smtp
      git pull origin main
      npm install
      pm2 restart nutaan-smtp
